version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    image: devops-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    image: devops-frontend
